export const experimentalWorks = {
  "distorted-mind": {
    title: "Distorted Mind",
    description:
      "A series of expressive self-portraits created during a time of intense self-loathing. The figure is drawn loosely, almost carelessly, to reflect a disconnection from self and a desire to strip away the polished surface. Spontaneous, erratic lines give the body a sense of movement, yet not graceful but restless. This motion echoes the inner turmoil: unstable thoughts, self-critical noise, and emotional dissonance.",
    images: [
      { id: 1, title: "Distorted Self #1", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527040/1_qsxuiq.jpg" },
      { id: 2, title: "Distorted Self #2", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527040/2_nlba83.jpg" },
      { id: 3, title: "Distorted Self #3", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527039/3_vxzons.jpg" },
    ],
    media: "Charcoal and Pencil Color on Paper",
    size: '12" × 15"',
    year: 2025,
  },
  "dream-montage": {
    title: "Dream Montage",
    description:
      "This body of work emerged from an experimental process rooted in dream observation. For one month, I kept a sketchbook and a set of colors beside my bed. Each morning, upon waking, I would immediately sketch any patterns, shapes, or objects I could recall from my dreams, often rough, fragmented memories. These spontaneous morning drawings became the foundation for a larger visual exploration. Using charcoal, ink, and gouache, I reassembled these elements into a layered pattern of images, somewhat a visual diary that traces the fleeting nature of the subconscious. The result is not a literal depiction of dreams, but a journey through their textures, moods, and symbolic remains.",
    images: [
      { id: 1, title: "Dream Fragment I", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527039/1_zmedgx.jpg" },
      { id: 2, title: "Dream Fragment II", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527041/2_g7cemt.jpg" },
      { id: 3, title: "Dream Fragment III", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527042/3_v76enw.jpg" },
      { id: 4, title: "Dream Sequence", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527040/4_j1kstw.jpg" },
      { id: 4, title: "Dream Sequence video", path: "https://res.cloudinary.com/dwe69wcqm/video/upload/v1764527041/vid_jie8bc.mp4"}
    ],
    media: "Gouache, Ink and Charcoal",
    size: "2ft × 10ft",
    year: 2025,
    hasVideo: true,
    videoPath: "/static/Experimental_works/Dream_Montage/vid.mp4",
  },
  "number-three": {
    title: "The Glory of Number Three",
    description:
      "This series contains 36 works, each individual work portraying the factuality of number three. The idea connects to the 'rule of three' and have a natural rhythm that feels more engaging and emotionally resonant. In numerical symbolism, three is kind of a perfect number. It's proven by neuroscientists that our brains like patterns and '3' happens to be the most basic pattern form, thus making it the easiest string of information for our brains to absorb and remember. I've always been fascinated by the number three and it feels complete, balanced, and somehow perfect. Over time, I began to notice how this number kept appearing in my own life and creative process. When setting up still life compositions, I often found myself drawn to triangular arrangements. I tended to create paintings in sets of three, and interestingly, many of my successful attempts came after the third trial.",
    images: [
      { id: 1, title: "Three Generations", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527041/1_yymwno.jpg" },
      { id: 2, title: "Triangle Composition", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527041/2_uc3ely.jpg" },
      { id: 3, title: "Three Elements", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527043/3_v4zwa1.jpg" },
      { id: 4, title: "Trinity", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527044/4_a08afc.jpg" },
      { id: 5, title: "Third Time's Charm", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527044/5_canpfk.jpg" },
      { id: 6, title: "Past Present Future", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527047/6_tl3tjv.jpg" },
      { id: 7, title: "Three Forms", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527047/7_j0nybc.jpg" },
      { id: 8, title: "Harmony of Three", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527046/8_djyrmh.jpg" },
    ],
    media: "Pen on Paper",
    size: "5ft × 4ft",
    year: 2024,
  },
  rickshaw: {
    title: "Chronicle of Rickshaw",
    description:
      "While working on my dissertation about rickshaw painting, a vibrant art form often seen on local, short-distance transportation, I found myself increasingly drawn to the pedal rickshaw itself. Its structure, curves, and vibrant color patterns inspired me beyond just the artwork. I began to see the rickshaw as more than a vehicle; it was a moving piece of art, deeply woven into the fabric of everyday life in Dhaka. This became a study-based exploration, where I roamed the streets of Dhaka, sketchbook in hand, quickly capturing fleeting moments of rickshaws in motion. These spontaneous drawings became my way of documenting not only the form and aesthetic of the rickshaw but also the atmosphere and spirit surrounding it. With the rise of electric rickshaws, traditional pedal rickshaws are gradually disappearing. My work became an attempt to preserve these fading glimpses of my favourite childhood vehicle. An effort to hold on to a piece of the city's memory before it's gone.",
    images: [
      { id: 1, title: "Rickshaw in Motion #1", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527046/1_ltbenx.jpg" },
      { id: 2, title: "Rickshaw in Motion #2", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527047/2_dpfa7g.jpg" },
      { id: 3, title: "Rickshaw Portrait #1", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527047/3_utcquy.jpg" },
      { id: 4, title: "Urban Vehicle Study", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527048/4_tcepxi.jpg" },
      { id: 5, title: "Heritage Transportation", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527053/5_ivmkyy.jpg" },
      { id: 6, title: "Dhaka Streets", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527048/6_vwozoe.jpg" },
      { id: 7, title: "Fading Memory", path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527048/7_h3otoq.jpg" },
    ],
    media: "Mixed Media on Paper",
    size: "Miniature",
    year: 2025,
  },
}

export const paintings = [
  {
    id: "p-1",
    title: "Departure of a Friend",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527050/1_lfdfbd.jpg",
    media: "Acrylic on Canvas",
    size: '24" × 24"',
    year: 2023,
  },
  {
    id: "p-2",
    title: "Gray Urban Song",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527048/2_q22ndu.jpg",
    media: "Acrylic on Canvas",
    size: "1ft × 10ft",
    year: 2024,
  },
  {
    id: "p-3",
    title: "Essence of Old Dhaka",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527049/3_ou5xef.jpg",
    media: "Pen on Paper",
    size: '5" × 22"',
    year: 2024,
  },
  {
    id: "p-4",
    title: "Motion of Three-Wheeler",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527050/4_lcuavm.jpg",
    media: "Acrylic on Canvas",
    size: "2ft × 5ft",
    year: 2025,
  },
  {
    id: "p-5",
    title: "Illusion",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527050/5_k1m0bw.jpg",
    media: "Acrylic on Canvas",
    size: '24" × 30"',
    year: 2025,
  },
  {
    id: "p-6",
    title: "Hostel Room Chronicles",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527051/6_r5naow.jpg",
    media: "Pen, Gouache and Pencil Color",
    size: "1.5ft × 3ft",
    year: 2025,
  },
  {
    id: "p-7",
    title: "Composition: Little Objects",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527052/7_tyosry.jpg",
    media: "Pen and Watercolor on Paper",
    size: '20" × 24"',
    year: 2025,
  },
  {
    id: "p-8",
    title: "Urban Landscape Study",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527052/8_cds4ag.jpg",
    media: "Acrylic on Canvas",
    size: '18" × 24"',
    year: 2024,
  },
]

export const panoramaWorks = [
  {
    id: "pn-1",
    title: "Panorama Study I",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527053/1_rtqgi6.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2024,
  },
  {
    id: "pn-2",
    title: "Panorama Study II",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527052/2_es8ulr.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2024,
  },
  {
    id: "pn-3",
    title: "Panorama Study III",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527052/3_ckuu1a.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2024,
  },
  {
    id: "pn-4",
    title: "Panorama Study IV",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527053/4_qqexvz.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2024,
  },
  {
    id: "pn-6",
    title: "Panorama Study VI",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527053/6_jplstp.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2025,
  },
  {
    id: "pn-7",
    title: "Panorama Study VII",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527054/7_bqbivf.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2025,
  },
  {
    id: "pn-8",
    title: "Panorama Study VIII",
    path: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527054/8_vvwgro.jpg",
    media: "Mixed Media",
    size: "Large Format",
    year: 2025,
  },
]

export const artistProfile = {
  name: "Madhubanti Biswas",
  profileImage: "https://res.cloudinary.com/dwe69wcqm/image/upload/v1764527055/me_sxnchl.jpg",
  email: "rayamadhubanti@gmail.com",
  phone: "+880 1880882341",
  location: "Dhanmondi, Dhaka, Bangladesh",
}
